# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.17/metricbeat-module-elasticsearch.html

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["http://elasticsearch:9200"]
  #username: "user"
  #password: "secret"
  #api_key: "foo:bar"
  username: ${ELASTICSEARCH_USERNAME:-beats_system}
  password: ${ELASTICSEARCH_PASSWORD:-changeme}

