# Module: logstash
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.17/metricbeat-module-logstash.html

- module: logstash
  xpack.enabled: true
  period: 10s
  hosts: ["http://logstash:9600"]
  #username: "user"
  #password: "secret"
  username: metricbeat_internal
  password: ${METRICBEAT_INTERNAL_PASSWORD}
