
- type: http
  id: elasticsearch-http
  name: Elasticsearch HTTP
  schedule: '@every 5s'
  urls:
    - http://elasticsearch:9200
  username: 'heartbeat_internal'
  password: '${HEARTBEAT_INTERNAL_PASSWORD}'

- type: icmp
  id: elasticsearch-icmp
  name: Elasticsearch ICMP
  schedule: '@every 5s'
  hosts:
    - elasticsearch
