## Metricbeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/metricbeat.docker.yml
#

name: metricbeat

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:http://elasticsearch:9200}'
  username: 'metricbeat_internal'
  password: '${METRICBEAT_INTERNAL_PASSWORD}'

setup.kibana.host: http://kibana:5601
system.hostfs: /hostfs

monitoring:
  enabled: true
  elasticsearch:
    username: 'beats_system'
    password: '${BEATS_SYSTEM_PASSWORD}'

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/metricbeat/current/http-endpoint.html
#

http:
  enabled: true
  host: 0.0.0.0
